namespace UI {
public enum ViewStateEnum {
    DETAIL,
    MEANDER_BOARD, // -> MEANDER_HAND, COMMAND_BOARD
    MEANDER_HAND, // MEANDER_BOARD <-
    COMMAND_BOARD, // MEANDER_BOARD <- -> COMMAND_HAND, DESIGNATE_BOARD
    COMMAND_HAND, // COMMAND_BOARD <- -> DESIGNATE_BOARD, DESIGNATE_HAND
    DESIGNATE_BOARD, // COMMAND_HAND, COMMAND_BOARD <- -> DESIGNATE_HAND
    DESIGNATE_HAND
}
}
