namespace UI {
public enum ViewStateEnum {
    SURRENDER,
    DETAIL,
    MEANDER_BOARD,
    MEANDER_HAND,
    COMMAND_HAND,
    COMMAND_LIST,
    DESIGNATE_BOARD,
    DESIGNATE_HAND,
    DESIGNATE_LIST,
    NONE
}
}
